### ISSUE TITLE
Restarted W10 node sometimes becomes stuck adding new block (onPersist insufficient funds)

### ISSUE THREAD

**Issue by EdgeDLT** [nspcc-dev/neo-go#3273] opened 2023-12-19 16:34 UTC
## Current Behavior
Attempting to start an out-of-sync node produces:

```
2023-12-19T15:57:41.356Z        WARN    blockQueue: failed adding block into the blockchain     {"error": "onPersist failed: VM has failed: at instruction 0 (SYSCALL): insufficient funds", "blockHeight": 4578499, "nextIndex": 4578500}
```

## Expected Behavior
The node should successfully sync the next block.

## Possible Solution
Something related to https://github.com/nspcc-dev/neo-go/pull/3110 maybe? Not looked too deep into it.

## Steps to Reproduce
1. Fully or partially sync a node then kill it.
2. Restart the node. If it progresses, kill it again.
3. Repeat 2 until the error occurs.

## Context
Ran into this issue with my indexer node. By default the node is not kept alive, it is fully synchronized then shut down once all operations are complete. Occasionally, but not always, starting the node again produces this error. If it does, no further progress can be made without a full resync.

## Your Environment

Windows 10
```
> ./neogo -v
NeoGo
Version: 0.104.0
GoVersion: go1.21.4
```

**Comment by roman-khimov** [comment] 2023-12-19 17:29
Are you using Level or Bolt?

**Comment by EdgeDLT** [comment] 2023-12-19 17:35
LevelDB.

**Comment by roman-khimov** [comment] 2023-12-19 17:38
That's more interesting. It obviously means a broken DB, but the way it's handled internally it's not trivial for it to get into this state. Yet if it happens, there should be a reason for that.

CC @532910.

**Comment by EdgeDLT** [comment] 2024-01-03 20:07
Uncovered some memory issues on my machine in recent days. Could well be a hardware fault that is responsible, so if you can't replicate, don't spend too long on it.

**Comment by AnnaShaleva** [comment] 2024-01-12 09:00
I was able to reproduce a similar bug on my local machine under the following conditions:
1. Low disk space left (< 100 Mb)
2. DB resync from trusted dump is started, but the process was killed by OOM killer.
3. DB resync from trusted dump is resumed and in a while I got:
```
2024-01-12T11:46:43.686+0300	WARN	contract invocation failed	{"tx": "591473831fa9508870afb22d89e595edb40306ff49bc2373d6b9bbc87abbda0e", "block": 2913226, "error": "at instruction 1 (SYSCALL): method 'Callback' not found"}
2024-01-12T11:46:43.700+0300	WARN	contract invocation failed	{"tx": "40d7d6be4922724174072b7c60f0cce175a0d470a23235b02e584fafcb9d0ec7", "block": 2913281, "error": "at instruction 1 (SYSCALL): method 'Callback' not found"}
2024-01-12T11:46:44.011+0300	INFO	shutting down service	{"service": "Prometheus", "endpoint": "[::]:2112"}
2024-01-12T11:47:21.743+0300	INFO	persisted to disk	{"blocks": 5852, "keys": 118232, "headerHeight": 2876784, "blockHeight": 2876783, "took": "43.997511933s"}
2024-01-12T11:47:36.029+0300	INFO	persisted to disk	{"blocks": 37886, "keys": 774298, "headerHeight": 2914670, "blockHeight": 2914669, "took": "14.285445886s"}
failed to add block 2914670: onPersist failed: VM has failed: at instruction 0 (SYSCALL): insufficient funds
```

I also was able to reproduce the same problem during network syncing with low disk space, so from my side this problem also seems to be connected with hardware problems.

**Comment by AnnaShaleva** [comment] 2024-01-12 18:57
I don't, I've removed the DB to test the compatibility, but for some reason I suspect that the problem can be reproduced. I'll try to reproduce it and save the DB to look at the diffs.

**Comment by fyfyrchik** [comment] 2024-04-05 15:53
I have reproduced the same problem with boltdb, but can't share the database, unfortunately.
My plan is to look into all the keys we have and look at the diff between corrupted db and freshly restored one.

@roman-khimov @AnnaShaleva Do you have any specific place in mind to look into?

**Comment by roman-khimov** [comment] 2024-04-05 16:54
Zero ideas on this one. It'd be cool if you'll be able to at least do the diff between proper state and whatever is in this broken DB. Luckily, your chain doesn't seem to be long.

**Comment by AnnaShaleva** [comment] 2024-05-17 13:11
@EdgeDLT, @fyfyrchik, please take a look at the https://github.com/nspcc-dev/neo-go/pull/3443. It should fix the problem, but it needs to be confirmed, thus I'm not closing this issue.

**Comment by AnnaShaleva** [comment] 2024-05-21 13:12
@EdgeDLT, @fyfyrchik, 0.106.0 is out, you may try it. Please, write back if succeeded.

**Comment by AnnaShaleva** [comment] 2024-09-09 10:41
It's been a while since #3443 is merged, this problem is solved.

**Closed by AnnaShaleva** 2024-09-09 10:41 UTC
Labels: bug, I3, U3, S4
