### ISSUE TITLE
neogo_current_block_height show 0 instead of real height

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#2970] opened 2023-04-13 12:10 UTC
neo-go version 0.78.4

```
% curl http://157.90.177.9:20332 --json '{"jsonrpc": "2.0", "method": "getblockcount", "params":[], "id": 1 }'
{"id":1,"jsonrpc":"2.0","result":8686678}
% curl http://157.90.177.18:20332 --json '{"jsonrpc": "2.0", "method": "getblockcount", "params":[], "id": 1 }'
{"id":1,"jsonrpc":"2.0","result":8686678}
```

```
% curl -s localhost:2202 | grep -i '^neogo_current_block_height'                                              
neogo_current_block_height 0
% curl -s localhost:2222 | grep -i '^neogo_current_block_height'
neogo_current_block_height 0
```

**Comment by 532910** [comment] 2023-04-13 13:53
no

**Comment by roman-khimov** [comment] 2023-04-14 09:37
This metric is updated upon new block processing, testnet is stuck at 8686678 for two weeks already, there are no new blocks therefore there are no metric updates. This is WONTFIX for Legacy, just because I don't want  to touch this codebase (the issue is far from being critical), but the same thing in fact can happen to N3 as well.

We need to update this (and other similar) metric on blockchain init as well, just to have valid data from the beginning.

**Closed** 2023-04-25 13:27 UTC
Labels: bug
