### ISSUE TITLE
RPC server fails to start with `address already in use` even though there are no other listeners

### ISSUE THREAD

**Issue by Alexpast1423** [nspcc-dev/neo-go#2771] opened 2022-10-28 11:17 UTC
After deploy cluster we can not deploy contract with error: 
```
2022-10-28 13:21:53  Error: initialization error: can't create N3 client: failed to get network magic: Post "http://172.26.161.85:40332": dial tcp 172.26.161.85:40332: connect: connection refused
2022-10-28 13:21:58  Error: can't to initialize context: can't create N3 client: failed to get network magic: Post "http://172.26.161.85:40332": dial tcp 172.26.161.85:40332: connect: connection refused
```

In morph-cn log I'm have that: 
```
Oct 28 10:53:42 az neo-go[14736]: 2022-10-28T10:53:42.452Z        INFO        approving block        {"height": 240, "hash": "2d42efea7fa47dced7f9242642417a015e877cfa7931257140fa42b7b0dcbe63", "tx_count": 0, "merkle": "000000000000000000>
Oct 28 10:53:42 az neo-go[14736]: 2022-10-28T10:53:42.453Z        INFO        initializing dbft        {"height": 241, "view": 0, "index": 0, "role": "Backup"}
Oct 28 10:53:43 az neo-go[14736]: 2022-10-28T10:53:43.086Z        INFO        persisted to disk        {"blocks": 1, "keys": 20, "headerHeight": 240, "blockHeight": 240, "took": "2.217064ms"}
Oct 28 10:53:43 az neo-go[14736]: 2022-10-28T10:53:43.879Z        INFO        Error encountered with rpc request        {"code": -100, "method": "getcontractstate", "params": "[1]"}
Oct 28 10:53:43 az neo-go[14736]: 2022-10-28T10:53:43.880Z        INFO        Error encountered with rpc request        {"code": -100, "method": "getcontractstate", "params": "[1]"}
Oct 28 10:53:49 az neo-go[14736]: 2022-10-28T10:53:49.375Z        INFO        Error encountered with rpc request        {"code": -100, "method": "getcontractstate", "params": "[1]"}
Oct 28 10:53:49 az neo-go[14736]: 2022-10-28T10:53:49.376Z        INFO        Error encountered with rpc request        {"code": -100, "method": "getcontractstate", "params": "[1]"}
```

I think that this log tell about correctly work of service
The network work, i'm check it with: 
```
curl -vk 172.26.161.85:40332
*   Trying 172.26.161.85:40332...
* Connected to 172.26.161.85 (172.26.161.85) port 40332 (#0)
> GET / HTTP/1.1
> Host: 172.26.161.85:40332
> User-Agent: curl/7.79.1
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 422 Unprocessable Entity
< Date: Fri, 28 Oct 2022 10:59:36 GMT
< Content-Length: 135
< Content-Type: text/plain; charset=utf-8
<
{"id":null,"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid Params","data":"invalid method 'GET', please retry with 'POST'"}}
* Connection #0 to host 172.26.161.85 left intact
```

i'm trying deploy contracts with incorrect wallets, and service work with it correctly: 

```
downloads/neofs-adm morph -c configuration/config.yaml init --contracts downloads/contract
Stage 1: transfer GAS to alphabet nodes.
Error: can't create transfer transaction: can't add system fee to transaction: bad vm state: FAULT due to an error: at instruction 94 (ASSERT): ASSERT failed
```

This tell about correctly work of service, but error on deploy contract tell about incorrectly service work ...

**Comment by fyrchik** [comment] 2022-10-28 12:29
The server is not available because it wasn't started at that moment, this it not a bug.
```
Oct 28 09:38:42 az neo-go[14511]: server error: listen tcp 0.0.0.0:40332: bind: address already in use
```

However I see following lines in logs:
```
Oct 28 09:38:42 az neo-go[14511]: 2022-10-28T09:38:42.266Z        INFO        new peer connected        {"addr": "172.26.161.139:40333", "peerCount": 4}
Oct 28 09:38:42 az neo-go[14511]: 2022-10-28T09:38:42.266Z        INFO        new peer connected        {"addr": "172.26.161.139:40332", "peerCount": 5}
Oct 28 09:38:42 az neo-go[14511]: 2022-10-28T09:38:42.266Z        WARN        peer disconnected        {"addr": "172.26.161.139:40332", "error": "already connected", "peerCount": 4}
Oct 28 09:38:42 az neo-go[14511]: 2022-10-28T09:38:42.266Z        WARN        peer disconnected        {"addr": "172.26.161.139:40333", "error": "unexpected empty payload: CMDVersion", "peer>
```
(NodePort=40333 , RPC port = 40332)

Node configuration seems OK (all seeds are properly configured with 4033 port).

**Comment by fyrchik** [comment] 2022-10-28 12:43
It looks like we have chosen to connect _from a random_ 40332 port and it later was advertised as a valid address.

**Comment by AnnaShaleva** [comment] 2022-10-28 12:56
We then probably need to carefully check the node port in order not to intersect with RPC or other services.

**Comment by roman-khimov** [comment] 2022-10-28 16:25
> It looks like we have chosen to connect _from a random_ 40332 port and it later was advertised as a valid address.

Rather a peer address, version exchange specifically contains proper port, so even if the node is to use an ephemeral 40332, its peer will know that the proper one is 40333.

NOBUG to me, to avoid it you can use <1024 ports.

**Comment by fyrchik** [comment] 2022-10-31 10:37
This seems to be fixed by setting `net.ipv4.ip_local_reserved_ports=40332`. We can't _completely_ fix it here anyway.

**Comment by Alexpast1423** [comment] 2022-11-02 09:54
We add port 40332 as reserved at system, but bug is actually today ...

**Comment by Alexpast1423** [comment] 2022-11-02 09:55
What info i can take for help in bug close ?

**Comment by AnnaShaleva** [comment] 2022-11-02 10:31
> It looks like we have chosen to connect from a random 40332 port and it later was advertised as a valid address.

Do you have `NodePort` set in your RPC server config? The only thing that comes to my mind is that it's empty and your RPC node is trying to choose any random free port, chooses RPC server's one (40332) and fails to start the RPC server after that. And what's the `NodePort` value of the cluster nodes?

>{"id":null,"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid Params","data":"invalid method 'GET', please retry with 'POST'"}}

This line is a valid RPC-server responce, so it was started by the moment you checked it, which means that both RPC node's network server and RPC server work well. If you're running nodes in docker, then are you sure that you have all address/port bindings properly set?

**Comment by AnnaShaleva** [comment] 2022-11-03 09:54
OK, we've discussed, it's not a bug from the neo-go side, the problem is in network settings.

**Closed by AnnaShaleva** 2022-11-03 09:54 UTC
