### ISSUE TITLE
transaction: Invocation TX with version == 0 not decoded

### ISSUE THREAD

**Issue by volekerb** [nspcc-dev/neo-go#569] opened 2019-12-21 13:16 UTC
Use
```
func getTX() *transaction.Transaction {
return &Transaction{
		Type:    InvocationType,
		Version: ,
		Data: &InvocationTX{
			Script:  script,
			Gas:     gas,
			Version: 1,
		},
		Attributes: []Attribute{},
		Inputs:     []Input{},
		Outputs:    []Output{},
		Scripts:    []Witness{},
	}
}
```
And test it with:
```

func TestMyself(t *testing.T) {
	tx := getTX()
	writer := io.NewBufBinWriter()
	tx.EncodeBinary(writer.BinWriter)
	hexed := hex.EncodeToString(writer.Bytes())

	fromHex, err := hex.DecodeString(hexed)
	require.NoError(t, err)
	r := io.NewBinReaderFromBuf(fromHex)
	tx := &transaction.Transaction{}
	tx.DecodeBinary(r)
	require.NoError(t, r.Err)
}
```
will return EOF.
Reason is covered in Encoding/Decoding:
```
// DecodeBinary implements Serializable interface.
func (tx *InvocationTX) DecodeBinary(br *io.BinReader) {
	tx.Script = br.ReadVarBytes()
	if tx.Version >= 1 {
		tx.Gas.DecodeBinary(br)
	} else {
		tx.Gas = util.Fixed8FromInt64(0)
	}
}

// EncodeBinary implements Serializable interface.
func (tx *InvocationTX) EncodeBinary(bw *io.BinWriter) {
	bw.WriteVarBytes(tx.Script)
	if tx.Version >= 1 {
		tx.Gas.EncodeBinary(bw)
	}
}
```

**Comment by volekerb** [comment] 2019-12-21 13:22
nit: there is no doc or any comment about version of the TX but in decoding/encoding we're relying on version == 1 which is not clear. I believe it's good to add godoc/comment in struct :
```
        // Version is always equal to 1 or.. ?
	Version uint8
```

**Comment by roman-khimov** [comment] 2019-12-22 08:53
It's not that we're relying on `version == 1`, it's that these versions (in `InvocationTX` and `Transaction`) must be consistent. It's a consequence of the `Version` field duplication that we currently have, caused by the need to encode/decode some fields conditionally based on transaction version. It can be solved in various ways like extending encoding/decoding functions with version parameter or adding `InvocationTXv0` and `InvocationTXv1`, but I'm not sure it's worth doing for 2.0.

**Comment by roman-khimov** [comment] 2020-03-16 12:36
I think we won't touch this for NEO 2.0 and 3.0 is a different beast, so it won't be an issue (at least before it's deployed).

-EWONTFIX.

**Closed by roman-khimov** 2020-03-16 12:36 UTC
Labels: bug
