### ISSUE TITLE
discrepancy in parsing witness scope format on RPC side

### ISSUE THREAD

**Issue by ixje** [nspcc-dev/neo-go#3059] opened 2023-07-10 11:14 UTC
The RPC method `invokescript`  supports passing optional `signers`. While investigating a wallet error reported by a user @hal0x2328 noticed that the Go node fails to parse a signer provided whereas the C# node doesn't.

Example request made;
```
{"params":["CxEMFM8qjpTLqLqEOKINSBGOosvj8jVKDBTPKo6Uy6i6hDiiDUgRjqLL4/I1ShTAHwwIdHJhbnNmZXIMFPVj6kC8KD1NDgXEjqMFs/Kgc0DvQWJ9W1I=",[{"account":"4a35f2e3cba28e11480da23884baa8cb948e2acf","scopes":1}]],"jsonrpc":"2.0","id":1234,"method":"invokescript"}
```

Go node response
```
{"id":1234,"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid Params","data":"not a signer: not a signer: json: cannot unmarshal number into Go struct field signerWithWitnessAux.scopes of type string"}}
```

Note how `scopes` is defined as a number not as a name of the flag, which C# successfully parses [here](https://github.com/neo-project/neo-modules/blob/b639e84c8fa7aa33c063ba764b27b9f93ef0ef04/src/RpcServer/RpcServer.SmartContract.cs#L171)

**Comment by roman-khimov** [comment] 2023-07-18 10:25
This in fact is a duplicate of #2563.

**Comment by ixje** [comment] 2023-07-18 11:29
from #2563 
> It can be fixed in future if there is a demand, but for now we'll keep the current behavior.

How much demand do we need? We currently have a proxy between our Go nodes to patch the request, but a proper fix like #3060 is a much nicer solution.

**Comment by roman-khimov** [comment] 2023-07-18 11:51
I'm _really_ surprised to see people using numeric inputs for this given that conversion from enumeration to JSON always produces strings and they're much more convenient in general. At the same time if this format is used by some software and people expect it to be supported (well, it's a second issue of this kind) we can adjust the node.

At the same time we'll still have some other types not covered, unfortunately.

**Comment by ixje** [comment] 2023-07-18 11:54
I'm fully with you that it is unfortunately supported on the C# side. It's kind of hard to track who's producing what though

**Closed** 2023-07-20 14:27 UTC
Labels: bug, rpc
