### ISSUE TITLE
NeoFSBlockFetcher may seem hanging

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#3721] opened 2024-12-04 02:14 UTC
with NeoFSBlockFetcher address set to ssl neogo silentlty doesn't work

steps to reproduce:
```Yaml
NeoFSBlockFetcher:
  Addresses:
    - st1.storage.fs.neo.org:443
    - st2.storage.fs.neo.org:443
    - st3.storage.fs.neo.org:443
    - st4.storage.fs.neo.org:443
```

log:
```
INFO        starting NeoFS BlockFetcher service
```

**Comment by AnnaShaleva** [comment] 2024-12-04 13:35
> neogo silentlty doesn't work

It works. BlockFetcher is trying to deal, and we have a relatively large deal timeout, so the error will be returned after timeout.

**Comment by 532910** [comment] 2024-12-04 14:50
deal timeout is not an answer, as reply happens instantly:
```
% curl -v http://st1.storage.fs.neo.org:443
* Host st1.storage.fs.neo.org:443 was resolved.
* IPv6: (none)
* IPv4: 157.90.176.145
*   Trying 157.90.176.145:443...
* Connected to st1.storage.fs.neo.org (157.90.176.145) port 443
* using HTTP/1.x
> GET / HTTP/1.1
> Host: st1.storage.fs.neo.org:443
> User-Agent: curl/8.11.0
> Accept: */*
> 
* Request completely sent off
< HTTP/1.1 400 Bad Request
< Server: nginx
< Date: Wed, 04 Dec 2024 14:50:10 GMT
< Content-Type: text/html
< Content-Length: 248
< Connection: close
< Strict-Transport-Security: max-age=63072000; includeSubDomains
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< 
<html>
<head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>The plain HTTP request was sent to HTTPS port</center>
<hr><center>nginx</center>
</body>
</html>
* shutting down connection #0
```

**Comment by roman-khimov** [comment] 2024-12-04 15:09
@cthulhu-rider probably knows something about it, I don't think it can be fixed with current SDK.

**Comment by AnnaShaleva** [comment] 2024-12-04 15:27
The problem is not on the NeoGo side. `pool.Dial` returns only after `n*DealTimeout` seconds where `n` is the number of nodes in the pool, so the problem is related to the pool itself.  The following code is responsible for initial pool dealing on the NeoGo side:
https://github.com/nspcc-dev/neo-go/blob/8952922c4d4f4474e390cf3afa4abcdf20c7960d/pkg/services/blockfetcher/blockfetcher.go#L202-L204
The result is (with smaller dial timeout):
```
2024-12-04T16:22:52.244+0300	INFO	starting NeoFS BlockFetcher service
2024-12-04T16:22:53.255+0300	INFO	persisted to disk	{"blocks": 0, "keys": 116, "headerHeight": 0, "blockHeight": 0, "took": "12.85244ms"}
2024-12-04T16:25:52.248+0300	ERROR	skipping NeoFS BlockFetcher	{"error": "failed to dial NeoFS pool: at least one node must be healthy"}
```

So @532910 you may submit an issue to the NeoFS SDK repo.

**Comment by cthulhu-rider** [comment] 2024-12-04 18:17
> @cthulhu-rider probably knows something about it, I don't think it can be fixed with current (as in version used by NeoGo) SDK.

the behavior is the same in the latest SDK. The error we receive from gRPC layer is
```
open gRPC connection: gRPC dial: context deadline exceeded: connection error: desc = "error reading server preface: http2: frame too large"
```
and gRPC dialer considers `reading server preface` as a _temporary_ error: it tries again until the deadline arrives

in opposite, NeoFS connection fails immediately on non-temporary failures. For example, both single client and pool return immediately if we set ports to `444`:
```
gRPC dial: connection error: desc = "transport: error while dialing: dial tcp 157.90.176.145:444: connect: connection refused"
```

---

@AnnaShaleva is right that pool's dial timeout sums all the client ones. And yeah, everything that can be improved in this area is located in the NeoFS SDK

**Comment by 532910** [comment] 2024-12-06 17:09
```
% journalctl -n1 -u neogo-morph-rpc          
Dec 06 14:36:14 tenes4 neogo-morph-rpc[446809]: INFO        starting NeoFS BlockFetcher service
% date
Fri  6 Dec 17:09:18 UTC 2024
```

**Closed** 2024-12-06 17:14 UTC
Labels: I3, U4, enhancement, S4
