### ISSUE TITLE
Make WS Client's error response more clear on reaching maximum number of subscribers

### ISSUE THREAD

**Issue by AnnaShaleva** [nspcc-dev/neo-go#2818] opened 2022-11-22 15:22 UTC
When maximum number of subscribers is reached, RPC server logs this error, but WS Client gets the response that is not that clear and unrelated to the subscribers. @carpawell, could you, please, attach the WS Client error text in this case? We need to make it more clear for the WS Client users.

**Comment by carpawell** [comment] 2022-11-22 18:18
@AnnaShaleva, I faced that kind of error on a machine that run a soft with a bug and kept restarting it (without clients closing):
```
websocket: bad handshake
```

Could be reproduced with that code sample:
```go
	for i := 0; i < 64; i++ {
		_, err := rpcclient.NewWS(context.Background(), "ws://morph-chain.neofs.devenv:30333/ws", rpcclient.Options{})
		if err != nil {
			panic(err)
		}
	}
```

On the server side i faced that:
```
Error encountered with rpc request      {"code": -32603, "cause": "websocket users limit reached", "method": "", "params": "[]"}
```

While that is a totally incorrect client usage, it is quite hard to debug such errors when the whole system behaves strangely. Also, I guess, having 64 WS connections could be a real situation and any additional client is not able to understand what is the reason for `websocket: bad handshake`. Seems like the WS client is not ready for HTTP responses until a protocol upgrade.

**Comment by roman-khimov** [comment] 2022-11-22 18:32
That's totally client-side:
> If the WebSocket handshake fails, ErrBadHandshake is returned along with a non-nil *http.Response so that callers can handle redirects, authentication, etcetera.

Server returns something useful in the response, but this data is ignored effectively.

**Closed** 2022-11-23 11:40 UTC
Labels: rpc
