### ISSUE TITLE
panic: flag provided but not defined

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neo-go#3184] opened 2023-11-01 15:59 UTC
I would not like to see this garbage:
```
panic: flag provided but not defined: -b

goroutine 1 [running]:
main.main()
	./main.go:13 +0x45
```

Steps to reproduce: `neogo -b`

**Comment by AnnaShaleva** [comment] 2023-11-01 16:02
Duplicate of https://github.com/nspcc-dev/neo-go/issues/2886.

**Closed by AnnaShaleva** 2023-11-01 16:02 UTC
Labels: bug
