### ISSUE TITLE
management.Update call scope is not sufficient for native contract calls

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neo-go#1990] opened 2021-06-02 15:20 UTC
neo-go v0.95.1

I got native contract call in `_deploy` method at `isUpdate` branch. If I use `management.Update` wrapper in `Migrate` method, then I got error `failed to invoke syscall 1381727586: missing call flags: 01011 vs 00101`. I tried `std.Serialize` and `crypto.Sha256` and they both produce this error.

If I use bigger scope as it shown in the [example](https://github.com/nspcc-dev/neo-go/blob/ed6652bf1f788d3aa05ebecd8ac3d996b50f9ec6/examples/timer/timer.go#L49), everything works fine.

Is it expected behavior? 

Code of the contract that fails at migration:
```go
package testcontract

import (
	"github.com/nspcc-dev/neo-go/pkg/interop/native/crypto"
	"github.com/nspcc-dev/neo-go/pkg/interop/native/management"
	"github.com/nspcc-dev/neo-go/pkg/interop/runtime"
	"github.com/nspcc-dev/neo-go/pkg/interop/storage"
)

const defaultTicks = 3
const mgmtKey = "mgmt"

var (
	ctx storage.Context
	ticksKey = []byte("ticks")
)

func init() {
	ctx = storage.GetContext()
}

func _deploy(_ interface{}, isUpdate bool) {
	if isUpdate {
		_ = crypto.Sha256(ticksKey) // <- place any native contract call here
		ticksLeft := storage.Get(ctx, ticksKey).(int) + 1
		storage.Put(ctx, ticksKey, ticksLeft)
		runtime.Log("One more tick is added.")
		return
	}
	sh := runtime.GetCallingScriptHash()
	storage.Put(ctx, mgmtKey, sh)
	storage.Put(ctx, ticksKey, defaultTicks)
}

// Migrate migrates the contract.
func Migrate(script []byte, manifest []byte) bool {
	management.Update(script, manifest)
	runtime.Log("Contract updated.")
	return true
}
```

**Comment by roman-khimov** [comment] 2021-06-02 16:13
That's an interesting case. It works as intended but at the same time it's not really user-friendly this way. The rule we have for native contract wrappers is that they're given exactly the set of permissions they need, no more and no less. And it works just fine for the primary purpose of any of these calls. But here you have a callback invoked from `management.Update` that technically needs more permissions (and I guess the same thing could happen to `management.Deploy`), so it fails.

So we either need to change the default permission set given to Deploy/Update, or add a parameter. None of these options seem good to me, but leaving it as is no good either.

**Comment by fyrchik** [comment] 2021-09-25 11:09
The issue also appeared during NNS contract update, where we calculate keys using hash-functions from native contracts. 
It was fixed in the contract itself
https://github.com/nspcc-dev/neofs-contract/commit/b2f6fb641a7966fcf1d076227a9c8de1836cb63e

**Comment by roman-khimov** [comment] 2022-01-17 21:54
We only call something from native contracts (which we have wrappers for) in these cases:
 * GAS/NEO transfers (`onNEP17Payment`)
   These have `contract.All` permissions, not a problem.
 * withdrawal from Notary contract (`transfer` of GAS contract is called)
   Has `contract.States` in interop, which looks like a bug to me (it calls `transfer`, so `AllowCall` is needed and transfer emits an event, so `AllowNotify` should also be present), but we can fix it easily. 
 * response transaction in Oracle contract (whatever callback is needed)
   Not something called by the user, not an issue.
 * and update/deploy from Management contract (calls to `_deploy`)
   These are problematic, they only require `callflag.States|callflag.AllowNotify` now, but they also do an internal call, so I think technically they also need an `AllowCall`. If we're to change the definition then it's going to be `contract.All` anyway and the problem will go away. This requires some synchronization with C# developers though.

@AnnaShaleva, @fyrchik, what do you think?

**Comment by AnnaShaleva** [comment] 2022-01-19 08:43
Yes, I agree with it, so the problem cases are the second (Notary's `withdraw`) and the last one (Management's update/deploy). If these methods use calls to other contracts and notifications, then they should explicitly require appropriate flags. The bug with Notary is fixed in a separate PR.

**Closed** 2022-02-01 09:30 UTC
Labels: question
